#!/bin/bash
# gitlab-api.sh — Create MR on wiki repo for generated docs
#
# Usage: bash gitlab-api.sh <PROJECT_NAME>
#
# Env vars required:
#   GITLAB_TOKEN — personal access token with api scope
#   WIKI_REPO — SSH URL of wiki repo (to derive project ID)

set -euo pipefail

PROJECT_NAME="${1:?Usage: gitlab-api.sh <PROJECT_NAME>}"
GITLAB_TOKEN="${GITLAB_TOKEN:-}"
WIKI_REPO="${WIKI_REPO:-git@gitlab.com:quocchung.nguyen/go-engineering-wiki.git}"

[ -z "$GITLAB_TOKEN" ] && echo "[gitlab] No GITLAB_TOKEN, skipping MR" && exit 0

# Extract GitLab project path from SSH URL
# git@gitlab.com:quocchung.nguyen/go-engineering-wiki.git → quocchung.nguyen/go-engineering-wiki
PROJECT_PATH=$(echo "$WIKI_REPO" | sed 's/.*://;s/\.git$//')
ENCODED_PATH=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$PROJECT_PATH', safe=''))")

GITLAB_API="https://gitlab.com/api/v4"

echo "[gitlab] Creating MR for $PROJECT_NAME on $PROJECT_PATH..."

# Check if MR already exists
EXISTING=$(curl -s -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
  "$GITLAB_API/projects/$ENCODED_PATH/merge_requests?source_branch=staging&target_branch=main&state=opened" \
  2>/dev/null || echo "[]")

MR_COUNT=$(echo "$EXISTING" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")

if [ "$MR_COUNT" -gt "0" ]; then
  MR_URL=$(echo "$EXISTING" | python3 -c "import json,sys; print(json.load(sys.stdin)[0].get('web_url',''))" 2>/dev/null)
  echo "[gitlab] MR already exists: $MR_URL"
  exit 0
fi

# Create MR: staging → main
RESULT=$(curl -s -X POST "$GITLAB_API/projects/$ENCODED_PATH/merge_requests" \
  -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
    \"source_branch\": \"staging\",
    \"target_branch\": \"main\",
    \"title\": \"docs($PROJECT_NAME): generate wiki documentation\",
    \"description\": \"Auto-generated by wiki-trainer.\\n\\nFiles:\\n- docs/$PROJECT_NAME/AGENT.md\\n- docs/$PROJECT_NAME/service.md\\n- docs/$PROJECT_NAME/contracts.md\",
    \"remove_source_branch\": false
  }" 2>/dev/null)

MR_URL=$(echo "$RESULT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('web_url','ERROR'))" 2>/dev/null || echo "ERROR")

if [ "$MR_URL" = "ERROR" ]; then
  echo "[gitlab] Failed to create MR: $RESULT"
  exit 1
fi

echo "[gitlab] MR created: $MR_URL"
